pull_request_rules:
  - name: Automatic merge security PRs when all status checks pass
    conditions:
      - author~=^(dependabot\[bot\]|renovate\[bot\])$
      - status-success=test-and-release
    actions:
      merge:
        method: rebase
        rebase_fallback: squash
      label:
        add:
          - mergify
