name: Build and Release

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Compile TypeScript
        run: npx tsc

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Build
        env:
          PUBLIC_VERSION: ${{ github.sha }}
          PUBLIC_SENTRY_DSN: ${{ vars.SENTRY_DSN }}
        run: npm run build

      - name: Install playwright
        run: npx playwright install

      - name: Run end-to-end tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.GITHUB_REPOSITORY }}-${{ github.sha }}
          path: build

      - name: Semantic release
        continue-on-error: true
        run: npx semantic-release
